# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vTqtSRMtfL2GAITWCP_pYTDau_9-u0-9
"""

pip install streamlit

import streamlit as st

st.write(""" # My first app Hello *word!*""")

